### ISSUE TITLE
Byte compilation raises warnings and exits with 1

### ISSUE THREAD

**Issue by terlar** [casouri/ghelp#1]
I was trying to byte-compile this, but it fails, I guess it is mainly due to the `geiser-doc` not being guarded (only via the main file). I think it is quite common practice to compile all the `el` files so it would be nice if that would work. Or should I make sure gesier exists during the byte compilation as well?

```
$ emacs -L . --batch -f batch-byte-compile *.el
Loading /nix/store/j7b4gj9q7frw194cpd4m7yikzyfjl2x1-emacs-git-with-packages-20201025.0/share/emacs/site-lisp/site-start.el (source)...

In end of data:
ghelp-builtin.el:435:1: Warning: the following functions are not known to be
    defined: help--symbol-completion-table,
    help-fns-function-description-header, help-fns--analyze-function,
    help-fns--key-bindings, help-fns--signature, help-fns--ensure-empty-line,
    help-fns-short-filename, cl--describe-class

In toplevel form:
ghelp-geiser.el:15:1: Error: Cannot open load file: No such file or directory, geiser-doc

In end of data:
ghelp-helpful.el:98:1: Warning: the following functions are not known to be
    defined: ghelp-get-page-data, ghelp-describe-1, ghelp-refresh

In end of data:
ghelp-test.el:56:1: Warning: the following functions are not known to be
    defined: ghelp-history--goto, ghelp-history-point, ghelp-history--find,
    ghelp-history--find-and-move, ghelp-history--forward, ghelp-history--back

In end of data:
ghelp.el:1192:1: Warning: the function ‘ghelp-geiser-backend’ is not known to
    be defined.
(1.34s) [1]
```

**Comment by casouri** [comment]
I pushed a commit that solves the warnings in ghelp.el and ghelp-test.el, now at least the remaining warnings look quite tidy:

```
In toplevel form:
ghelp-eglot.el:13:1: Error: Cannot open load file: No such file or directory, eglot

In toplevel form:
ghelp-geiser.el:15:1: Error: Cannot open load file: No such file or directory, geiser-doc

In toplevel form:
ghelp-helpful.el:13:1: Error: Cannot open load file: No such file or directory, helpful
```

I don't have a good idea of how to fix the warnings for the backend files, though. Technically, they should be included in each of those projects instead of ghelp. But obviously that's not going to happen, so we are stuck with these hacks.

Now, I could have used declare-function, but the eglot backend uses some custom macros defined by eglot, so there will still be errors.

**Comment by terlar** [comment]
Okay, thank you, for now I solved it by providing those packages at compile-time. But not having those warnings will make it quicker to spot what is failing. I guess you can close this if there is no workaround for these packages.

**Comment by casouri** [comment]
Why not having those warnings makes it quicker to spot the problem?

**Comment by terlar** [comment]
I meant it was quicker to spot the problem/errors now after your fix. Since it is only the errors and no warnings. :)

**Comment by casouri** [comment]
I see :-) Then I'll close this for now.
