### ISSUE TITLE
ghelp-describe-variable seems to have some issues (when helpful is not required)

### ISSUE THREAD

**Issue by terlar** [casouri/ghelp#2]
If you run `ghelp-describe-variable` without first `(require 'helpful)`, it breaks and you loose a lot of information from `helpful-variable`. If I first require it works as expected. It would be nice if `ghelp` would require what is used or autoload on invocation so you could have a lazy loaded `helpful` package.

![Screenshot from 2020-11-06 09-31-29](https://user-images.githubusercontent.com/280235/98372086-80be9680-203d-11eb-8e2a-200fd06bf275.png)

**Comment by casouri** [comment]
I'm trying to fix the breakage in the basic help result. As for requiring helpful. I don't have a good idea yet.

**Comment by casouri** [comment]
Without fixing the builtin Help bug, I made ghelp to load helpful.el automatically if it is in the load-path:
```
(when (find-library-name "helpful")
  (require 'ghelp-helpful)
  (ghelp-register-backend 'emacs-lisp-mode #'ghelp-helpful-backend))
```

**Comment by terlar** [comment]
Nice, this is working, thank you for this, now I can lazy load helpful again!

**Comment by terlar** [comment]
I didn't notice until now that this introduced some issues when byte-compiling, I see the following:
```
Cannot load ghelp: (void-function find-library-name)
```

So I think you might need to require it:
```
(require 'find-func)
```

**Comment by casouri** [comment]
Thanks, didn't know that's not loaded by default. I've added the require form.

**Comment by terlar** [comment]
Thank you once again!
