### ISSUE TITLE
There is no ghelp buffer in list-buffers

### ISSUE THREAD

**Issue by krdzo** [casouri/ghelp#5]
Hi. If I run this: 
```M-x ghelp-describe-function RET setq```
I get a `*ghelp emacs-lisp-mode : setq*` buffer. 
If then I close this buffer with `q` it wanishes, it can't be found with `list-buffers`. 

Is there a way that the `*ghelp emacs-lisp-mode :...*` buffer shows in `list-buffers` or `switch-to-buffer` prompt and if there isn't a way can you add it. 
It would be great if for every different mode in `ghelp-history-alist` we got a separate ghelp buffer, 
i.e. if in `ghelp-history-alist` there are histories for `js-mode`, `go-mode` and `emacs-lisp-mode` we got  `*ghelp js-mode...*`, `*ghelp go-mode...*` and  `*ghelp emacs-lisp-mode...*` buffers.

**Comment by casouri** [comment]
Hey sorry I forgot about this issue.  ghelp buffers are hidden from normal buffer list to not clutter it up. If you want to see them, just type a space in `list-buffers` then you should see the ghelp buffers.

**Comment by krdzo** [comment]
Ah ok, I didn't know about hidden buffers. Thank you
